"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
type Event = { id: string; actor?: string | null; action: string; entityType: string; entityLabel?: string | null; details?: string | null; createdAt: string };
export default function AuditLogPage() {
 const [items,setItems]=useState<Event[]>([]); const [error,setError]=useState(""); const [search,setSearch]=useState("");
 useEffect(()=>{fetch("/api/audit-log",{cache:"no-store"}).then(async r=>{const j=await r.json();if(!r.ok)throw new Error(j.error||"Unable to load audit trail");setItems(j.data||[])}).catch(e=>setError(e instanceof Error?e.message:"Unable to load audit trail"))},[]);
 const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return q?items.filter(x=>[x.actor,x.action,x.entityType,x.entityLabel,x.details].some(v=>String(v??"").toLowerCase().includes(q))):items},[items,search]);
 return <main className="content standalone vercel-colour-module audit-page"><style>{`.vercel-colour-module{background:#f7f8fa;color:#111827;min-height:100vh}.vercel-colour-module .eyebrow{color:#64748b}.vercel-colour-module h1,.vercel-colour-module h2,.vercel-colour-module strong{color:#111827}.vercel-colour-module p{color:#64748b}.vercel-colour-module .workspace-card,.vercel-colour-module .kpi-card{background:#fff;border-color:#e5e7eb;box-shadow:0 1px 2px rgba(15,23,42,.03)}.vercel-colour-module .section-label,.vercel-colour-module .kpi-card span{color:#64748b}.audit-list{display:grid;gap:10px}.audit-event{border:1px solid #e2e8f0;border-radius:10px;padding:14px 16px;background:#fff}.audit-event:hover{border-color:#cbd5e1;box-shadow:0 2px 8px rgba(15,23,42,.04)}.audit-event-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.audit-event-meta{color:#64748b;font-size:11px;margin-top:5px}.audit-event-details{margin:8px 0 0;color:#475569;font-size:12px}.audit-search{min-width:260px;border:1px solid #e2e8f0;border-radius:8px;background:#fff;color:#111827;padding:10px 11px}.audit-empty{border:1px dashed #cbd5e1;border-radius:10px;padding:38px 20px;text-align:center;color:#64748b}@media(max-width:700px){.audit-event-head{display:block}.audit-search{width:100%;min-width:0;margin-top:12px}}`}</style>
 <header className="topbar"><div><div className="eyebrow">System · Governance</div><h1>Audit Trail</h1><p>Chronological record of project workflow events and system activity.</p></div><Link className="secondary-button" href="/settings">Settings</Link></header>
 <section className="kpi-grid"><div className="kpi-card"><span>Total Events</span><strong>{items.length}</strong><small>Recorded activity</small></div><div className="kpi-card"><span>Visible Events</span><strong>{filtered.length}</strong><small>Current filter</small></div><div className="kpi-card"><span>Actors</span><strong>{new Set(items.map(x=>x.actor||"System")).size}</strong><small>Unique sources</small></div><div className="kpi-card"><span>Entity Types</span><strong>{new Set(items.map(x=>x.entityType)).size}</strong><small>Tracked areas</small></div></section>
 <section className="workspace-card"><div className="list-toolbar"><div><div className="section-label">Activity register</div><h2>{filtered.length} event{filtered.length===1?'':'s'}</h2></div><input className="audit-search" aria-label="Search audit trail" placeholder="Search actor, action, entity..." value={search} onChange={e=>setSearch(e.target.value)}/></div>
 {error&&<div className="audit-empty"><strong>Unable to load audit trail</strong><p>{error}</p></div>}
 {!error&&!filtered.length&&<div className="audit-empty"><strong>{items.length?'No matching events':'No audit events recorded yet.'}</strong><span>{items.length?'Try a different search.':'System workflow activity will appear here.'}</span></div>}
 {!error&&filtered.length>0&&<div className="audit-list">{filtered.map(item=><article className="audit-event" key={item.id}><div className="audit-event-head"><div><strong>{item.action}</strong><div className="audit-event-meta">{item.entityType}{item.entityLabel?` · ${item.entityLabel}`:""} · {item.actor||"System"}</div></div><span className="status ready">{new Date(item.createdAt).toLocaleString()}</span></div>{item.details&&<p className="audit-event-details">{item.details}</p>}</article>)}</div>}
 </section></main>;
}
