"use client";

import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";

type Project={id:string;code:string;name:string};
type Option={id:string;label?:string;title?:string;drawingNumber?:string;itemCode?:string;activityCode?:string;name?:string;description?:string;subject?:string};
type Rfi={id:string;projectId:string;rfiNumber:string;subject:string;question:string;response?:string|null;status:string;raisedBy?:string|null;assignedTo?:string|null;priority?:string|null;dueDate?:string|null;responseDate?:string|null;drawingId?:string|null;boqItemId?:string|null;constructionActivityId?:string|null;notes?:string|null;reference?:string|null;createdAt?:string};
const statuses=["Open","Under Review","Answered","Closed","Cancelled"],priorities=["Low","Medium","High","Critical"];
async function json(r:Response){const t=await r.text();try{return t?JSON.parse(t):{}}catch{return {}}}
const dateValue=(v?:string|null)=>v?new Date(v).toISOString().slice(0,10):"";
export default function RfisPage(){
 const [projects,setProjects]=useState<Project[]>([]),[projectId,setProjectId]=useState(""),[rows,setRows]=useState<Rfi[]>([]),[drawings,setDrawings]=useState<Option[]>([]),[boq,setBoq]=useState<Option[]>([]),[activities,setActivities]=useState<Option[]>([]);
 const [editing,setEditing]=useState<string|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[search,setSearch]=useState("");
 const [form,setForm]=useState<any>({rfiNumber:"",subject:"",question:"",response:"",status:"Open",raisedBy:"",assignedTo:"",priority:"Medium",dueDate:"",responseDate:"",drawingId:"",boqItemId:"",constructionActivityId:"",notes:"",reference:""});
 const load=async()=>{if(!projectId)return;const q=encodeURIComponent(projectId);const [r,d,b,a]=await Promise.all([fetch(`/api/workspace?module=rfis&projectId=${q}`,{cache:"no-store"}),fetch(`/api/workspace?module=drawings&projectId=${q}`,{cache:"no-store"}),fetch(`/api/workspace?module=boq&projectId=${q}`,{cache:"no-store"}),fetch(`/api/construction?projectId=${q}`,{cache:"no-store"})]);const rd=await json(r),dd=await json(d),bd=await json(b),ad=await json(a);setRows(Array.isArray(rd.data)?rd.data:[]);setDrawings(Array.isArray(dd.data)?dd.data:[]);setBoq(Array.isArray(bd.data)?bd.data:[]);setActivities(Array.isArray(ad.data)?ad.data:[])};
 useEffect(()=>{(async()=>{const r=await fetch("/api/projects",{cache:"no-store"}),d=await json(r),p=Array.isArray(d.data)?d.data:[];setProjects(p);if(p[0])setProjectId(x=>x||p[0].id)})()},[]); useEffect(()=>{void load()},[projectId]);
 const set=(k:string,v:string)=>setForm((f:any)=>({...f,[k]:v}));
 const submit=async(e:FormEvent)=>{e.preventDefault();if(!projectId||!form.rfiNumber.trim()||!form.subject.trim()||!form.question.trim()){setMessage("Project, RFI Number, Subject and Question are required.");return}setBusy(true);setMessage("");const payload={...form,projectId,dueDate:form.dueDate?new Date(form.dueDate).toISOString():null,responseDate:form.responseDate?new Date(form.responseDate).toISOString():null,drawingId:form.drawingId||null,boqItemId:form.boqItemId||null,constructionActivityId:form.constructionActivityId||null};try{const url=`/api/workspace?module=rfis${editing?`&id=${editing}`:""}`,r=await fetch(url,{method:editing?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}),d=await json(r);if(!r.ok)throw Error(d.error||"Unable to save RFI");setMessage(editing?"RFI updated.":"RFI created.");setEditing(null);setForm({rfiNumber:"",subject:"",question:"",response:"",status:"Open",raisedBy:"",assignedTo:"",priority:"Medium",dueDate:"",responseDate:"",drawingId:"",boqItemId:"",constructionActivityId:"",notes:"",reference:""});await load()}catch(x){setMessage(x instanceof Error?x.message:"Unable to save RFI")}finally{setBusy(false)}};
 const edit=(r:Rfi)=>{setEditing(r.id);setForm({...r,dueDate:dateValue(r.dueDate),responseDate:dateValue(r.responseDate),drawingId:r.drawingId||"",boqItemId:r.boqItemId||"",constructionActivityId:r.constructionActivityId||""});window.scrollTo({top:0,behavior:"smooth"})};
 const remove=async(id:string)=>{if(!confirm("Delete this RFI?"))return;setBusy(true);const r=await fetch(`/api/workspace?module=rfis&id=${id}`,{method:"DELETE"});const d=await json(r);setMessage(r.ok?"RFI deleted.":d.error||"Unable to delete RFI");await load();setBusy(false)};
 const filtered=useMemo(()=>rows.filter(r=>!search.trim()||Object.values(r).some(v=>String(v??"").toLowerCase().includes(search.toLowerCase()))),[rows,search]);
 return <main className="content standalone"><header className="topbar"><div><div className="eyebrow">Project governance</div><h1>RFIs</h1><p>Requests for information linked to drawings, BOQ and construction execution.</p></div><Link className="secondary-button" href="/approvals">Approvals</Link></header>
 <section className="kpi-grid"><div className="kpi-card"><span>Total</span><strong>{rows.length}</strong></div><div className="kpi-card"><span>Open</span><strong>{rows.filter(r=>r.status.toLowerCase()==="open").length}</strong></div><div className="kpi-card"><span>Under Review</span><strong>{rows.filter(r=>r.status.toLowerCase().includes("review")).length}</strong></div><div className="kpi-card"><span>Overdue</span><strong>{rows.filter(r=>r.dueDate&&new Date(r.dueDate)<new Date()&&!['Closed','Cancelled','Answered'].includes(r.status)).length}</strong></div></section>
 <section className="workspace-card"><div className="section-label">Project</div><select value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="">Select project</option>{projects.map(p=><option key={p.id} value={p.id}>{p.code} · {p.name}</option>)}</select></section>
 <section className="workspace-card"><div className="section-label">{editing?"Edit RFI":"New RFI"}</div><form className="form-grid" onSubmit={submit}>
 {[["RFI Number","rfiNumber"],["Subject","subject"],["Raised By","raisedBy"],["Assigned To","assignedTo"],["Reference","reference"]].map(([l,k])=><label key={k}>{l}<input value={form[k]} onChange={e=>set(k,e.target.value)} /></label>)}
 <label>Priority<select value={form.priority} onChange={e=>set("priority",e.target.value)}>{priorities.map(x=><option key={x}>{x}</option>)}</select></label><label>Status<select value={form.status} onChange={e=>set("status",e.target.value)}>{statuses.map(x=><option key={x}>{x}</option>)}</select></label>
 <label>Due Date<input type="date" value={form.dueDate} onChange={e=>set("dueDate",e.target.value)}/></label><label>Response Date<input type="date" value={form.responseDate} onChange={e=>set("responseDate",e.target.value)}/></label>
 <label>Drawing<select value={form.drawingId} onChange={e=>set("drawingId",e.target.value)}><option value="">None</option>{drawings.map(x=><option key={x.id} value={x.id}>{x.drawingNumber} · {x.title}</option>)}</select></label>
 <label>BOQ Item<select value={form.boqItemId} onChange={e=>set("boqItemId",e.target.value)}><option value="">None</option>{boq.map(x=><option key={x.id} value={x.id}>{x.itemCode} · {x.description}</option>)}</select></label>
 <label>Construction Activity<select value={form.constructionActivityId} onChange={e=>set("constructionActivityId",e.target.value)}><option value="">None</option>{activities.map(x=><option key={x.id} value={x.id}>{x.activityCode} · {x.name}</option>)}</select></label>
 <label className="form-span-2">Question<textarea required value={form.question} onChange={e=>set("question",e.target.value)}/></label><label className="form-span-2">Response<textarea value={form.response} onChange={e=>set("response",e.target.value)}/></label><label className="form-span-2">Notes<textarea value={form.notes} onChange={e=>set("notes",e.target.value)}/></label>
 <div><button className="primary-button" disabled={busy}>{busy?"Saving...":editing?"Update RFI":"Create RFI"}</button>{editing&&<button type="button" className="secondary-button" onClick={()=>setEditing(null)}>Cancel</button>}</div></form>{message&&<p className="form-message">{message}</p>}</section>
 <section className="workspace-card"><div className="list-toolbar"><div><div className="section-label">Register</div><h2>{filtered.length} RFIs</h2></div><input placeholder="Search RFIs" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="table-wrap"><table><thead><tr><th>RFI</th><th>Subject</th><th>Priority</th><th>Status</th><th>Due</th><th>Actions</th></tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td>{r.rfiNumber}</td><td>{r.subject}</td><td>{r.priority||"Medium"}</td><td>{r.status}</td><td>{dateValue(r.dueDate)||""}</td><td><button className="secondary-button" onClick={()=>edit(r)}>Edit</button> <button className="secondary-button" disabled={busy} onClick={()=>void remove(r.id)}>Delete</button></td></tr>)}</tbody></table></div></section></main>;
}
