"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";

type Status = "planned" | "in_progress" | "completed" | "on_hold";
type ConstructionActivity = { id:string; projectId:string; boqItemId:string|null; activityCode:string; name:string; discipline:string|null; contractor:string|null; status:Status; progress:number; plannedQuantity:string|number; actualQuantity:string|number; unit:string|null; plannedStart:string|null; plannedEnd:string|null; actualStart:string|null; actualEnd:string|null; notes:string|null; updatedAt:string };
type Project = { id:string; code:string; name:string };
type BoqItem = { id:string; itemCode:string; description:string; quantity:string|number; unit:string };
type FormState = { projectId:string; boqItemId:string; activityCode:string; name:string; discipline:string; contractor:string; status:Status; progress:number; plannedQuantity:number; actualQuantity:number; unit:string; plannedStart:string; plannedEnd:string; actualStart:string; actualEnd:string; notes:string };

const statuses:Status[]=["planned","in_progress","completed","on_hold"];
const statusLabel:Record<Status,string>={planned:"Planned",in_progress:"In progress",completed:"Completed",on_hold:"On hold"};
const disciplines=["Site works","Earthworks","Foundations","Concrete works","Masonry","Structural steel","Roofing","Finishes","Doors and windows","External works","Roads and drainage","MEP installation","Testing and commissioning","Other"];
const units=["m3","m2","m","kg","t","No.","set","lot","item","day","hour"];
const emptyForm:FormState={projectId:"",boqItemId:"",activityCode:"",name:"",discipline:"Site works",contractor:"",status:"planned",progress:0,plannedQuantity:0,actualQuantity:0,unit:"m3",plannedStart:"",plannedEnd:"",actualStart:"",actualEnd:"",notes:""};
function numberValue(value:string|number){return Number(value??0)}
function formatDate(value:string|null){if(!value)return "Not set";const d=new Date(value);return Number.isNaN(d.getTime())?"Not set":new Intl.DateTimeFormat(undefined,{year:"numeric",month:"short",day:"numeric"}).format(d)}
function formatQuantity(value:string|number){return new Intl.NumberFormat(undefined,{maximumFractionDigits:3}).format(numberValue(value))}
function iso(value:string){return value?new Date(value).toISOString():null}
function localDate(value:string|null){if(!value)return "";const d=new Date(value);if(Number.isNaN(d.getTime()))return "";const pad=(n:number)=>String(n).padStart(2,"0");return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`}

export default function ConstructionPage(){
 const [projects,setProjects]=useState<Project[]>([]),[activities,setActivities]=useState<ConstructionActivity[]>([]),[boqItems,setBoqItems]=useState<BoqItem[]>([]),[form,setForm]=useState<FormState>(emptyForm),[editingId,setEditingId]=useState<string|null>(null),[filterProject,setFilterProject]=useState("all"),[filterStatus,setFilterStatus]=useState<"all"|Status>("all"),[query,setQuery]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");try{const [pr,ar]=await Promise.all([fetch("/api/projects",{cache:"no-store"}),fetch("/api/construction",{cache:"no-store"})]);const pd=await pr.json(),ad=await ar.json();if(!pr.ok)throw new Error(pd.error??"Unable to load projects.");if(!ar.ok)throw new Error(ad.error??"Unable to load construction activities.");const rows=Array.isArray(pd.data)?pd.data:[];setProjects(rows);setActivities(Array.isArray(ad.data)?ad.data:[]);if(!form.projectId&&rows[0]?.id)setForm(f=>({...f,projectId:rows[0].id}));}catch(e){setError(e instanceof Error?e.message:"Unable to load construction data.")}finally{setLoading(false)}},[form.projectId]);
 useEffect(()=>{void load()},[load]);
 useEffect(()=>{if(!form.projectId){setBoqItems([]);return}void (async()=>{try{const r=await fetch(`/api/workspace?module=boq&projectId=${encodeURIComponent(form.projectId)}`,{cache:"no-store"});const d=await r.json();setBoqItems(r.ok&&Array.isArray(d.data)?d.data:[])}catch{setBoqItems([])}})()},[form.projectId]);
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return activities.filter(a=>{const pm=filterProject==="all"||a.projectId===filterProject,sm=filterStatus==="all"||a.status===filterStatus,text=`${a.activityCode} ${a.name} ${a.discipline??""} ${a.contractor??""} ${a.unit??""} ${a.notes??""}`.toLowerCase();return pm&&sm&&(!q||text.includes(q))})},[activities,filterProject,filterStatus,query]);
 const projectName=(id:string)=>projects.find(p=>p.id===id)?.name??"Unknown project";
 const reset=()=>{setForm(projects[0]?.id?{...emptyForm,projectId:projects[0].id}:emptyForm);setEditingId(null)};
 const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setSaving(true);setError("");setMessage("");if(form.plannedStart&&form.plannedEnd&&new Date(form.plannedEnd)<new Date(form.plannedStart)){setError("Planned end cannot be before planned start.");setSaving(false);return}if(form.actualStart&&form.actualEnd&&new Date(form.actualEnd)<new Date(form.actualStart)){setError("Actual end cannot be before actual start.");setSaving(false);return}try{const payload={...form,boqItemId:form.boqItemId||null,discipline:form.discipline||null,contractor:form.contractor||null,unit:form.unit||null,plannedStart:iso(form.plannedStart),plannedEnd:iso(form.plannedEnd),actualStart:iso(form.actualStart),actualEnd:iso(form.actualEnd),notes:form.notes||null,progress:Number(form.progress),plannedQuantity:Number(form.plannedQuantity),actualQuantity:Number(form.actualQuantity)};const r=await fetch(editingId?`/api/construction/${editingId}`:"/api/construction",{method:editingId?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw new Error(d.error??"Unable to save construction activity.");setMessage(editingId?"Construction activity updated successfully.":"Construction activity created successfully.");reset();await load()}catch(e){setError(e instanceof Error?e.message:"Unable to save construction activity.")}finally{setSaving(false)}};
 const edit=(a:ConstructionActivity)=>{setEditingId(a.id);setForm({projectId:a.projectId,boqItemId:a.boqItemId??"",activityCode:a.activityCode,name:a.name,discipline:a.discipline??"",contractor:a.contractor??"",status:a.status,progress:a.progress,plannedQuantity:numberValue(a.plannedQuantity),actualQuantity:numberValue(a.actualQuantity),unit:a.unit??"",plannedStart:localDate(a.plannedStart),plannedEnd:localDate(a.plannedEnd),actualStart:localDate(a.actualStart),actualEnd:localDate(a.actualEnd),notes:a.notes??""});setMessage("");window.scrollTo({top:0,behavior:"smooth"})};
 const remove=async(a:ConstructionActivity)=>{if(!window.confirm(`Delete construction activity ${a.activityCode} from ${projectName(a.projectId)}?`))return;try{const r=await fetch(`/api/construction/${a.id}`,{method:"DELETE"});const d=await r.json();if(!r.ok)throw new Error(d.error??"Unable to delete construction activity.");setMessage("Construction activity deleted successfully.");if(editingId===a.id)reset();await load()}catch(e){setError(e instanceof Error?e.message:"Unable to delete construction activity.")}};
 const inProgress=activities.filter(a=>a.status==="in_progress").length,completed=activities.filter(a=>a.status==="completed").length,average=activities.length?Math.round(activities.reduce((s,a)=>s+a.progress,0)/activities.length):0,plannedTotal=activities.reduce((s,a)=>s+numberValue(a.plannedQuantity),0),actualTotal=activities.reduce((s,a)=>s+numberValue(a.actualQuantity),0);
 return <main className="projects-page construction-page"><header className="projects-header"><div><div className="eyebrow">Creative Studios / Construction</div><h1>Construction</h1><p>Control site execution against BOQ, programme dates, quantities, contractors and progress.</p></div><a className="back-link" href="/">Dashboard</a></header>
 <section className="project-stats"><div className="project-stat"><span>Total activities</span><strong>{activities.length}</strong></div><div className="project-stat"><span>In progress</span><strong>{inProgress}</strong></div><div className="project-stat"><span>Completed</span><strong>{completed}</strong></div><div className="project-stat"><span>Average progress</span><strong>{average}%</strong></div><div className="project-stat"><span>Planned quantity</span><strong>{formatQuantity(plannedTotal)}</strong></div><div className="project-stat"><span>Actual quantity</span><strong>{formatQuantity(actualTotal)}</strong></div></section>
 {(error||message)&&<div className={error?"project-alert error":"project-alert success"} role="status">{error||message}</div>}
 {projects.length===0&&!loading?<section className="project-empty"><strong>Create a project first</strong><span>Construction activities must belong to a project.</span><a className="back-link" href="/projects">Open Projects</a></section>:<section className="project-layout"><form className="project-form" onSubmit={submit}><div className="section-label">{editingId?"Edit activity":"New activity"}</div><h2>{editingId?"Update construction activity":"Add construction activity"}</h2><p>Execution records are linked to the selected project and can reference a BOQ item.</p><div className="form-grid">
 <label>Project<select value={form.projectId} onChange={e=>setForm({...form,projectId:e.target.value,boqItemId:""})} required><option value="" disabled>Select project</option>{projects.map(p=><option key={p.id} value={p.id}>{p.code} · {p.name}</option>)}</select></label>
 <label>BOQ item<select value={form.boqItemId} onChange={e=>setForm({...form,boqItemId:e.target.value})}><option value="">Not linked</option>{boqItems.map(b=><option key={b.id} value={b.id}>{b.itemCode} · {b.description}</option>)}</select></label>
 <label>Activity code<input value={form.activityCode} onChange={e=>setForm({...form,activityCode:e.target.value})} placeholder="CON-001" maxLength={80} required/></label><label>Contractor / team<input value={form.contractor} onChange={e=>setForm({...form,contractor:e.target.value})} placeholder="Main contractor / site team" maxLength={200}/></label>
 <label className="full-width">Activity name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Excavate foundation trenches" maxLength={250} required/></label>
 <label>Discipline<select value={form.discipline} onChange={e=>setForm({...form,discipline:e.target.value})}>{disciplines.map(d=><option key={d}>{d}</option>)}</select></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value as Status})}>{statuses.map(s=><option key={s} value={s}>{statusLabel[s]}</option>)}</select></label>
 <label>Planned quantity<input type="number" min={0} step="0.001" value={form.plannedQuantity} onChange={e=>setForm({...form,plannedQuantity:Math.max(0,Number(e.target.value))})}/></label><label>Actual quantity<input type="number" min={0} step="0.001" value={form.actualQuantity} onChange={e=>setForm({...form,actualQuantity:Math.max(0,Number(e.target.value))})}/></label><label>Unit<select value={form.unit} onChange={e=>setForm({...form,unit:e.target.value})}><option value="">Not specified</option>{units.map(u=><option key={u}>{u}</option>)}</select></label><label>Progress (%)<input type="number" min={0} max={100} step={1} value={form.progress} onChange={e=>setForm({...form,progress:Math.min(100,Math.max(0,Number(e.target.value)))})}/></label>
 <label>Planned start<input type="datetime-local" value={form.plannedStart} onChange={e=>setForm({...form,plannedStart:e.target.value})}/></label><label>Planned finish<input type="datetime-local" value={form.plannedEnd} onChange={e=>setForm({...form,plannedEnd:e.target.value})}/></label><label>Actual start<input type="datetime-local" value={form.actualStart} onChange={e=>setForm({...form,actualStart:e.target.value})}/></label><label>Actual finish<input type="datetime-local" value={form.actualEnd} onChange={e=>setForm({...form,actualEnd:e.target.value})}/></label>
 <label className="full-width">Notes<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} placeholder="Site notes, constraints, inspections or coordination comments" rows={4} maxLength={4000}/></label></div><div className="form-actions">{editingId&&<button type="button" className="secondary-button" onClick={reset}>Cancel</button>}<button type="submit" className="primary-button" disabled={saving}>{saving?"Saving...":editingId?"Save changes":"Add construction activity"}</button></div></form>
 <section className="project-list-panel"><div className="list-toolbar"><div><div className="section-label">Construction register</div><h2>{filtered.length} activit{filtered.length===1?"y":"ies"}</h2></div><button className="secondary-button" onClick={()=>void load()} disabled={loading}>Refresh</button></div><div className="filters"><input aria-label="Search construction activities" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search code, activity, contractor or notes"/><select value={filterProject} onChange={e=>setFilterProject(e.target.value)}><option value="all">All projects</option>{projects.map(p=><option key={p.id} value={p.id}>{p.code}</option>)}</select><select value={filterStatus} onChange={e=>setFilterStatus(e.target.value as "all"|Status)}><option value="all">All statuses</option>{statuses.map(s=><option key={s} value={s}>{statusLabel[s]}</option>)}</select></div>
 {loading?<div className="project-empty"><strong>Loading construction register...</strong><span>Reading site execution records.</span></div>:filtered.length===0?<div className="project-empty"><strong>No construction activities found</strong><span>Create an activity or change the filters.</span></div>:<div className="project-table-wrap"><table className="project-table"><thead><tr><th>Code</th><th>Project</th><th>Activity</th><th>Contractor</th><th>Status</th><th>Progress</th><th>Programme</th><th>Updated</th><th/></tr></thead><tbody>{filtered.map(a=><tr key={a.id}><td><strong>{a.activityCode}</strong>{a.boqItemId&&<div className="project-description">BOQ linked</div>}</td><td><strong>{projects.find(p=>p.id===a.projectId)?.code??"Unknown"}</strong><div className="project-description">{projectName(a.projectId)}</div></td><td><div className="project-name">{a.name}</div><div className="project-description">{a.discipline||"General"} · {formatQuantity(a.actualQuantity)} / {formatQuantity(a.plannedQuantity)} {a.unit??""}</div></td><td>{a.contractor||"Not assigned"}</td><td><span className={`project-status ${a.status}`}>{statusLabel[a.status]}</span></td><td><strong>{a.progress}%</strong></td><td><div>{formatDate(a.plannedStart)} → {formatDate(a.plannedEnd)}</div><div className="project-description">Actual: {formatDate(a.actualStart)} → {formatDate(a.actualEnd)}</div></td><td>{formatDate(a.updatedAt)}</td><td><div className="row-actions"><button onClick={()=>edit(a)}>Edit</button><button className="danger-link" onClick={()=>void remove(a)}>Delete</button></div></td></tr>)}</tbody></table></div>}</section></section>}</main>;
}
