"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";

type Status = "planned" | "in_progress" | "completed" | "on_hold";
type Discipline = "mechanical" | "electrical" | "plumbing" | "fire_protection" | "hvac" | "public_health" | "other";
type Project = { id: string; code: string; name: string };
type Drawing = { id: string; projectId: string; drawingNumber: string; title: string };
type MepWork = { id: string; projectId: string; drawingId: string | null; discipline: Discipline; category: string; description: string; specification: string | null; status: Status; progress: number; notes: string | null; updatedAt: string };
type FormState = { projectId: string; drawingId: string; discipline: Discipline; category: string; description: string; specification: string; status: Status; progress: number; notes: string };

const statuses: Status[] = ["planned", "in_progress", "completed", "on_hold"];
const statusLabel: Record<Status, string> = { planned: "Planned", in_progress: "In progress", completed: "Completed", on_hold: "On hold" };
const disciplines: Discipline[] = ["mechanical", "electrical", "plumbing", "fire_protection", "hvac", "public_health", "other"];
const disciplineLabel: Record<Discipline, string> = { mechanical: "Mechanical", electrical: "Electrical", plumbing: "Plumbing", fire_protection: "Fire protection", hvac: "HVAC", public_health: "Public health", other: "Other" };
const categories: Record<Discipline, string[]> = {
  mechanical: ["Plant and equipment", "Pumping", "Ventilation", "Mechanical services", "Other"],
  electrical: ["Power distribution", "Lighting", "Small power", "Earthing and lightning protection", "Low voltage systems", "Other"],
  plumbing: ["Cold water", "Hot water", "Sanitary drainage", "Rainwater", "Plumbing fixtures", "Other"],
  fire_protection: ["Fire water", "Sprinkler system", "Fire hose reels", "Fire detection", "Fire alarm", "Other"],
  hvac: ["Air conditioning", "Ductwork", "Ventilation", "Refrigeration", "Controls", "Other"],
  public_health: ["Water supply", "Wastewater", "Sanitation", "Stormwater", "Other"],
  other: ["Specialist services", "Coordination", "Other"],
};
const emptyForm: FormState = { projectId: "", drawingId: "", discipline: "electrical", category: "Power distribution", description: "", specification: "", status: "planned", progress: 0, notes: "" };

function formatDate(value: string) { const date = new Date(value); return Number.isNaN(date.getTime()) ? "Not set" : new Intl.DateTimeFormat(undefined, { year: "numeric", month: "short", day: "numeric" }).format(date); }

export default function MepPage() {
  const [projects, setProjects] = useState<Project[]>([]); const [drawings, setDrawings] = useState<Drawing[]>([]); const [works, setWorks] = useState<MepWork[]>([]);
  const [form, setForm] = useState<FormState>(emptyForm); const [editingId, setEditingId] = useState<string | null>(null); const [filterProject, setFilterProject] = useState("all"); const [filterDiscipline, setFilterDiscipline] = useState<"all" | Discipline>("all"); const [filterStatus, setFilterStatus] = useState<"all" | Status>("all"); const [query, setQuery] = useState(""); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [message, setMessage] = useState("");

  const load = useCallback(async () => { setLoading(true); setError(""); try { const [p, d, m] = await Promise.all([fetch("/api/projects", { cache: "no-store" }), fetch("/api/drawings", { cache: "no-store" }), fetch("/api/mep", { cache: "no-store" })]); const [pd, dd, md] = await Promise.all([p.json(), d.json(), m.json()]); if (!p.ok) throw new Error(pd.error ?? "Unable to load projects."); if (!d.ok) throw new Error(dd.error ?? "Unable to load drawings."); if (!m.ok) throw new Error(md.error ?? "Unable to load MEP records."); const projectRows = Array.isArray(pd.data) ? pd.data : []; setProjects(projectRows); setDrawings(Array.isArray(dd.data) ? dd.data : []); setWorks(Array.isArray(md.data) ? md.data : []); if (!form.projectId && projectRows[0]?.id) setForm((current) => ({ ...current, projectId: projectRows[0].id })); } catch (err) { setError(err instanceof Error ? err.message : "Unable to load MEP data."); } finally { setLoading(false); } }, [form.projectId]);
  useEffect(() => { void load(); }, [load]);

  const availableDrawings = useMemo(() => drawings.filter((drawing) => drawing.projectId === form.projectId), [drawings, form.projectId]);
  const filtered = useMemo(() => { const q = query.trim().toLowerCase(); return works.filter((work) => { const projectMatch = filterProject === "all" || work.projectId === filterProject; const disciplineMatch = filterDiscipline === "all" || work.discipline === filterDiscipline; const statusMatch = filterStatus === "all" || work.status === filterStatus; const text = `${work.category} ${work.description} ${work.specification ?? ""} ${work.notes ?? ""}`.toLowerCase(); return projectMatch && disciplineMatch && statusMatch && (!q || text.includes(q)); }); }, [filterProject, filterDiscipline, filterStatus, query, works]);
  const projectName = (id: string) => projects.find((project) => project.id === id)?.name ?? "Unknown project";
  const drawingLabel = (id: string | null) => { if (!id) return "Not linked"; const drawing = drawings.find((row) => row.id === id); return drawing ? `${drawing.drawingNumber} · ${drawing.title}` : "Unknown drawing"; };
  const reset = () => { setForm(projects[0]?.id ? { ...emptyForm, projectId: projects[0].id } : emptyForm); setEditingId(null); };
  const changeDiscipline = (discipline: Discipline) => setForm((current) => ({ ...current, discipline, category: categories[discipline][0] }));

  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSaving(true); setError(""); setMessage(""); try { const response = await fetch(editingId ? `/api/mep/${editingId}` : "/api/mep", { method: editingId ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, drawingId: form.drawingId || null, progress: Number(form.progress), specification: form.specification || null, notes: form.notes || null }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "Unable to save MEP work."); setMessage(editingId ? "MEP work updated successfully." : "MEP work created successfully."); reset(); await load(); } catch (err) { setError(err instanceof Error ? err.message : "Unable to save MEP work."); } finally { setSaving(false); } };
  const edit = (work: MepWork) => { setEditingId(work.id); setForm({ projectId: work.projectId, drawingId: work.drawingId ?? "", discipline: work.discipline, category: work.category, description: work.description, specification: work.specification ?? "", status: work.status, progress: work.progress, notes: work.notes ?? "" }); setMessage(""); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const remove = async (work: MepWork) => { if (!window.confirm(`Delete this ${disciplineLabel[work.discipline]} work item from ${projectName(work.projectId)}?`)) return; setError(""); setMessage(""); try { const response = await fetch(`/api/mep/${work.id}`, { method: "DELETE" }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "Unable to delete MEP work."); setMessage("MEP work deleted successfully."); if (editingId === work.id) reset(); await load(); } catch (err) { setError(err instanceof Error ? err.message : "Unable to delete MEP work."); } };

  const inProgress = works.filter((work) => work.status === "in_progress").length; const completed = works.filter((work) => work.status === "completed").length; const averageProgress = works.length ? Math.round(works.reduce((sum, work) => sum + work.progress, 0) / works.length) : 0;

  return <main className="projects-page mep-page">
    <header className="projects-header"><div><div className="eyebrow">Creative Studios / MEP</div><h1>MEP Services</h1><p>Coordinate mechanical, electrical, plumbing, fire protection, HVAC and public health services against project drawings.</p></div><a className="back-link" href="/">Dashboard</a></header>
    <section className="project-stats" aria-label="MEP summary"><div className="project-stat"><span>Total work items</span><strong>{works.length}</strong></div><div className="project-stat"><span>In progress</span><strong>{inProgress}</strong></div><div className="project-stat"><span>Completed</span><strong>{completed}</strong></div><div className="project-stat"><span>Average progress</span><strong>{averageProgress}%</strong></div></section>
    {(error || message) && <div className={error ? "project-alert error" : "project-alert success"} role="status">{error || message}</div>}
    {projects.length === 0 && !loading ? <section className="project-empty"><strong>Create a project first</strong><span>MEP records must belong to a project. Open Projects to create the project record.</span><a className="back-link" href="/projects">Open Projects</a></section> : <section className="project-layout">
      <form className="project-form" onSubmit={submit}><div className="section-label">{editingId ? "Edit MEP work" : "New MEP work"}</div><h2>{editingId ? "Update service record" : "Add service record"}</h2><p>Link MEP scope to the project and, where applicable, the controlling drawing.</p>
        <div className="form-grid">
          <label>Project<select value={form.projectId} onChange={(event) => setForm({ ...form, projectId: event.target.value, drawingId: "" })} required><option value="" disabled>Select project</option>{projects.map((project) => <option key={project.id} value={project.id}>{project.code} · {project.name}</option>)}</select></label>
          <label>Drawing<select value={form.drawingId} onChange={(event) => setForm({ ...form, drawingId: event.target.value })}><option value="">Not linked</option>{availableDrawings.map((drawing) => <option key={drawing.id} value={drawing.id}>{drawing.drawingNumber} · {drawing.title}</option>)}</select></label>
          <label>Discipline<select value={form.discipline} onChange={(event) => changeDiscipline(event.target.value as Discipline)}>{disciplines.map((discipline) => <option key={discipline} value={discipline}>{disciplineLabel[discipline]}</option>)}</select></label>
          <label>Category<select value={form.category} onChange={(event) => setForm({ ...form, category: event.target.value })}>{categories[form.discipline].map((category) => <option key={category}>{category}</option>)}</select></label>
          <label className="full-width">Description<textarea value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} placeholder="Describe the service, design scope, installation package or coordination activity" rows={4} maxLength={2000} required /></label>
          <label className="full-width">Specification<textarea value={form.specification} onChange={(event) => setForm({ ...form, specification: event.target.value })} placeholder="Equipment, capacity, material, standard, design requirement or installation specification" rows={4} maxLength={4000} /></label>
          <label>Status<select value={form.status} onChange={(event) => setForm({ ...form, status: event.target.value as Status })}>{statuses.map((status) => <option key={status} value={status}>{statusLabel[status]}</option>)}</select></label>
          <label>Progress (%)<input type="number" min={0} max={100} step={1} value={form.progress} onChange={(event) => setForm({ ...form, progress: Math.min(100, Math.max(0, Number(event.target.value))) })} /></label>
          <label className="full-width">Notes<textarea value={form.notes} onChange={(event) => setForm({ ...form, notes: event.target.value })} placeholder="Coordination notes, design comments or site requirements" rows={3} maxLength={4000} /></label>
        </div>
        <div className="form-actions">{editingId && <button type="button" className="secondary-button" onClick={reset}>Cancel</button>}<button type="submit" className="primary-button" disabled={saving}>{saving ? "Saving..." : editingId ? "Save changes" : "Add MEP work"}</button></div>
      </form>
      <section className="project-list-panel"><div className="list-toolbar"><div><div className="section-label">MEP register</div><h2>{filtered.length} work item{filtered.length === 1 ? "" : "s"}</h2></div><button className="secondary-button" onClick={() => void load()} disabled={loading}>Refresh</button></div>
        <div className="filters"><input aria-label="Search MEP works" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search category, description or specification" /><select value={filterProject} onChange={(event) => setFilterProject(event.target.value)}><option value="all">All projects</option>{projects.map((project) => <option key={project.id} value={project.id}>{project.code}</option>)}</select><select value={filterDiscipline} onChange={(event) => setFilterDiscipline(event.target.value as "all" | Discipline)}><option value="all">All disciplines</option>{disciplines.map((discipline) => <option key={discipline} value={discipline}>{disciplineLabel[discipline]}</option>)}</select><select value={filterStatus} onChange={(event) => setFilterStatus(event.target.value as "all" | Status)}><option value="all">All statuses</option>{statuses.map((status) => <option key={status} value={status}>{statusLabel[status]}</option>)}</select></div>
        {loading ? <div className="project-empty"><strong>Loading MEP register...</strong><span>Reading project service records.</span></div> : filtered.length === 0 ? <div className="project-empty"><strong>No MEP work found</strong><span>Create an item or change the filters.</span></div> : <div className="project-table-wrap"><table className="project-table"><thead><tr><th>Project</th><th>Discipline</th><th>Scope</th><th>Status</th><th>Progress</th><th>Drawing</th><th>Updated</th><th /></tr></thead><tbody>{filtered.map((work) => <tr key={work.id}><td><strong>{projects.find((project) => project.id === work.projectId)?.code ?? "Unknown"}</strong><div className="project-description">{projectName(work.projectId)}</div></td><td><strong>{disciplineLabel[work.discipline]}</strong><div className="project-description">{work.category}</div></td><td><div className="project-name">{work.description}</div><div className="project-description">{work.specification || "No specification"}</div></td><td><span className={`project-status ${work.status}`}>{statusLabel[work.status]}</span></td><td><strong>{work.progress}%</strong></td><td>{drawingLabel(work.drawingId)}</td><td>{formatDate(work.updatedAt)}</td><td><div className="row-actions"><button onClick={() => edit(work)}>Edit</button><button className="danger-link" onClick={() => void remove(work)}>Delete</button></div></td></tr>)}</tbody></table></div>}
      </section>
    </section>}
  </main>;
}
