"use client";

import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";

type Project={id:string;code:string;name:string}; type Option={id:string;title?:string;drawingNumber?:string;rfiNumber?:string};
type Approval={id:string;projectId:string;approvalNumber?:string|null;subject:string;approvalType:string;status:string;requestedBy?:string|null;reviewer?:string|null;dueDate?:string|null;submittedAt?:string|null;decidedAt?:string|null;documentId?:string|null;drawingId?:string|null;rfiId?:string|null;comments?:string|null;createdAt?:string};
const statuses=["Pending","In Review","Approved","Rejected","Returned","Cancelled"],types=["Drawing","Document","BOQ","RFI Response","Material","Method Statement","Design Decision","Other"];
async function json(r:Response){const t=await r.text();try{return t?JSON.parse(t):{}}catch{return {}}} const dateValue=(v?:string|null)=>v?new Date(v).toISOString().slice(0,10):"";
export default function ApprovalsPage(){
 const [projects,setProjects]=useState<Project[]>([]),[projectId,setProjectId]=useState(""),[rows,setRows]=useState<Approval[]>([]),[docs,setDocs]=useState<Option[]>([]),[drawings,setDrawings]=useState<Option[]>([]),[rfis,setRfis]=useState<Option[]>([]),[editing,setEditing]=useState<string|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[search,setSearch]=useState("");
 const [form,setForm]=useState<any>({approvalNumber:"",subject:"",approvalType:"Drawing",status:"Pending",requestedBy:"",reviewer:"",dueDate:"",submittedAt:"",decidedAt:"",documentId:"",drawingId:"",rfiId:"",comments:""});
 const load=async()=>{if(!projectId)return;const q=encodeURIComponent(projectId);const [a,d,dr,r]=await Promise.all([fetch(`/api/workspace?module=approvals&projectId=${q}`,{cache:"no-store"}),fetch(`/api/workspace?module=documents&projectId=${q}`,{cache:"no-store"}),fetch(`/api/workspace?module=drawings&projectId=${q}`,{cache:"no-store"}),fetch(`/api/workspace?module=rfis&projectId=${q}`,{cache:"no-store"})]);const [ad,dd,drd,rd]=await Promise.all([json(a),json(d),json(dr),json(r)]);setRows(Array.isArray(ad.data)?ad.data:[]);setDocs(Array.isArray(dd.data)?dd.data:[]);setDrawings(Array.isArray(drd.data)?drd.data:[]);setRfis(Array.isArray(rd.data)?rd.data:[])};
 useEffect(()=>{(async()=>{const r=await fetch("/api/projects",{cache:"no-store"}),d=await json(r),p=Array.isArray(d.data)?d.data:[];setProjects(p);if(p[0])setProjectId(x=>x||p[0].id)})()},[]); useEffect(()=>{void load()},[projectId]);
 const set=(k:string,v:string)=>setForm((f:any)=>({...f,[k]:v}));
 const submit=async(e:FormEvent)=>{e.preventDefault();if(!projectId||!form.subject.trim()||!form.approvalType){setMessage("Project, Subject and Approval Type are required.");return}setBusy(true);setMessage("");const iso=(v:string)=>v?new Date(v).toISOString():null;const payload={...form,projectId,approvalNumber:form.approvalNumber||null,dueDate:iso(form.dueDate),submittedAt:iso(form.submittedAt),decidedAt:iso(form.decidedAt),documentId:form.documentId||null,drawingId:form.drawingId||null,rfiId:form.rfiId||null};try{const r=await fetch(`/api/workspace?module=approvals${editing?`&id=${editing}`:""}`,{method:editing?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}),d=await json(r);if(!r.ok)throw Error(d.error||"Unable to save approval");setMessage(editing?"Approval updated.":"Approval created.");setEditing(null);setForm({approvalNumber:"",subject:"",approvalType:"Drawing",status:"Pending",requestedBy:"",reviewer:"",dueDate:"",submittedAt:"",decidedAt:"",documentId:"",drawingId:"",rfiId:"",comments:""});await load()}catch(x){setMessage(x instanceof Error?x.message:"Unable to save approval")}finally{setBusy(false)}};
 const edit=(r:Approval)=>{setEditing(r.id);setForm({...r,dueDate:dateValue(r.dueDate),submittedAt:dateValue(r.submittedAt),decidedAt:dateValue(r.decidedAt),documentId:r.documentId||"",drawingId:r.drawingId||"",rfiId:r.rfiId||""});window.scrollTo({top:0,behavior:"smooth"})};
 const remove=async(id:string)=>{if(!confirm("Delete this approval request?"))return;setBusy(true);const r=await fetch(`/api/workspace?module=approvals&id=${id}`,{method:"DELETE"}),d=await json(r);setMessage(r.ok?"Approval deleted.":d.error||"Unable to delete approval");await load();setBusy(false)};
 const filtered=useMemo(()=>rows.filter(r=>!search.trim()||Object.values(r).some(v=>String(v??"").toLowerCase().includes(search.toLowerCase()))),[rows,search]);
 return <main className="content standalone"><header className="topbar"><div><div className="eyebrow">Project governance</div><h1>Approvals</h1><p>Controlled review of drawings, documents, BOQ items, RFI responses and design decisions.</p></div><Link className="secondary-button" href="/rfis">RFIs</Link></header>
 <section className="kpi-grid"><div className="kpi-card"><span>Total</span><strong>{rows.length}</strong></div><div className="kpi-card"><span>Pending</span><strong>{rows.filter(r=>r.status.toLowerCase()==="pending").length}</strong></div><div className="kpi-card"><span>In Review</span><strong>{rows.filter(r=>r.status.toLowerCase().includes("review")).length}</strong></div><div className="kpi-card"><span>Overdue</span><strong>{rows.filter(r=>r.dueDate&&new Date(r.dueDate)<new Date()&&!['Approved','Rejected','Cancelled'].includes(r.status)).length}</strong></div></section>
 <section className="workspace-card"><div className="section-label">Project</div><select value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="">Select project</option>{projects.map(p=><option key={p.id} value={p.id}>{p.code} · {p.name}</option>)}</select></section>
 <section className="workspace-card"><div className="section-label">{editing?"Edit approval":"New approval"}</div><form className="form-grid" onSubmit={submit}>
 {[['Approval Number','approvalNumber'],['Subject','subject'],['Requested By','requestedBy'],['Reviewer / Approver','reviewer']].map(([l,k])=><label key={k}>{l}<input value={form[k]} onChange={e=>set(k,e.target.value)}/></label>)}
 <label>Approval Type<select value={form.approvalType} onChange={e=>set("approvalType",e.target.value)}>{types.map(x=><option key={x}>{x}</option>)}</select></label><label>Status<select value={form.status} onChange={e=>set("status",e.target.value)}>{statuses.map(x=><option key={x}>{x}</option>)}</select></label>
 <label>Due Date<input type="date" value={form.dueDate} onChange={e=>set("dueDate",e.target.value)}/></label><label>Submitted Date<input type="date" value={form.submittedAt} onChange={e=>set("submittedAt",e.target.value)}/></label><label>Decision Date<input type="date" value={form.decidedAt} onChange={e=>set("decidedAt",e.target.value)}/></label>
 <label>Document<select value={form.documentId} onChange={e=>set("documentId",e.target.value)}><option value="">None</option>{docs.map(x=><option key={x.id} value={x.id}>{x.title}</option>)}</select></label><label>Drawing<select value={form.drawingId} onChange={e=>set("drawingId",e.target.value)}><option value="">None</option>{drawings.map(x=><option key={x.id} value={x.id}>{x.drawingNumber} · {x.title}</option>)}</select></label><label>RFI<select value={form.rfiId} onChange={e=>set("rfiId",e.target.value)}><option value="">None</option>{rfis.map(x=><option key={x.id} value={x.id}>{x.rfiNumber} · {x.subject}</option>)}</select></label>
 <label className="form-span-2">Comments / Decision<textarea value={form.comments} onChange={e=>set("comments",e.target.value)}/></label><div><button className="primary-button" disabled={busy}>{busy?"Saving...":editing?"Update Approval":"Create Approval"}</button>{editing&&<button type="button" className="secondary-button" onClick={()=>setEditing(null)}>Cancel</button>}</div></form>{message&&<p className="form-message">{message}</p>}</section>
 <section className="workspace-card"><div className="list-toolbar"><div><div className="section-label">Register</div><h2>{filtered.length} approval requests</h2></div><input placeholder="Search approvals" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="table-wrap"><table><thead><tr><th>Number</th><th>Subject</th><th>Type</th><th>Status</th><th>Due</th><th>Actions</th></tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td>{r.approvalNumber||"Approval"}</td><td>{r.subject}</td><td>{r.approvalType}</td><td>{r.status}</td><td>{dateValue(r.dueDate)||""}</td><td><button className="secondary-button" onClick={()=>edit(r)}>Edit</button> <button className="secondary-button" disabled={busy} onClick={()=>void remove(r.id)}>Delete</button></td></tr>)}</tbody></table></div></section></main>;
}
