import { boolean, decimal, integer, pgEnum, pgTable, text, timestamp, uuid } from "drizzle-orm/pg-core";

export const projectStatus = pgEnum("project_status", ["planning", "active", "on_hold", "completed", "cancelled"]);
export const workStatus = pgEnum("work_status", ["planned", "in_progress", "completed", "on_hold"]);
export const drawingDiscipline = pgEnum("drawing_discipline", ["architectural", "structural"]);
export const mepDiscipline = pgEnum("mep_discipline", ["mechanical", "electrical", "plumbing", "fire_protection", "hvac", "public_health", "other"]);
export const procurementStatus = pgEnum("procurement_status", ["draft", "requested", "approved", "ordered", "partially_received", "received", "cancelled"]);

export const projects = pgTable("projects", {
  id: uuid("id").defaultRandom().primaryKey(), code: text("code").notNull().unique(), name: text("name").notNull(), clientName: text("client_name"), location: text("location"), description: text("description"), status: projectStatus("status").default("planning").notNull(), startDate: timestamp("start_date", { withTimezone: true }), targetEndDate: timestamp("target_end_date", { withTimezone: true }), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
});
export const architectureWorks = pgTable("architecture_works", { id: uuid("id").defaultRandom().primaryKey(), projectId: uuid("project_id").references(() => projects.id, { onDelete: "cascade" }).notNull(), category: text("category").notNull(), description: text("description").notNull(), status: workStatus("status").default("planned").notNull(), progress: integer("progress").default(0).notNull(), notes: text("notes"), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull() });
export const engineeringWorks = pgTable("engineering_works", { id: uuid("id").defaultRandom().primaryKey(), projectId: uuid("project_id").references(() => projects.id, { onDelete: "cascade" }).notNull(), category: text("category").notNull(), description: text("description").notNull(), status: workStatus("status").default("planned").notNull(), progress: integer("progress").default(0).notNull(), notes: text("notes"), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull() });
export const drawings = pgTable("drawings", {
  id: uuid("id").defaultRandom().primaryKey(), projectId: uuid("project_id").references(() => projects.id, { onDelete: "cascade" }).notNull(), drawingNumber: text("drawing_number").notNull(), title: text("title").notNull(), discipline: text("discipline").notNull(), drawingType: text("drawing_type").default("Plan").notNull(), revision: text("revision").default("A").notNull(), status: text("status").default("Draft").notNull(), scale: text("scale").default("1:100"), fileUrl: text("file_url"), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
});
export const mepWorks = pgTable("mep_works", { id: uuid("id").defaultRandom().primaryKey(), projectId: uuid("project_id").references(() => projects.id, { onDelete: "cascade" }).notNull(), drawingId: uuid("drawing_id").references(() => drawings.id, { onDelete: "set null" }), discipline: mepDiscipline("discipline").notNull(), category: text("category").notNull(), description: text("description").notNull(), specification: text("specification"), status: workStatus("status").default("planned").notNull(), progress: integer("progress").default(0).notNull(), notes: text("notes"), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull() });
export const boqItems = pgTable("boq_items", { id: uuid("id").defaultRandom().primaryKey(), projectId: uuid("project_id").references(() => projects.id, { onDelete: "cascade" }).notNull(), drawingId: uuid("drawing_id").references(() => drawings.id, { onDelete: "set null" }), itemCode: text("item_code").notNull(), category: text("category").notNull(), element: text("element").notNull(), description: text("description").notNull(), quantity: decimal("quantity", { precision: 14, scale: 3 }).default("0").notNull(), unit: text("unit").notNull(), rate: decimal("rate", { precision: 14, scale: 2 }).default("0").notNull(), amount: decimal("amount", { precision: 16, scale: 2 }).default("0").notNull(), status: workStatus("status").default("planned").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull() });
export const suppliers = pgTable("suppliers", { id: uuid("id").defaultRandom().primaryKey(), code: text("code").notNull().unique(), name: text("name").notNull(), contactName: text("contact_name"), email: text("email"), phone: text("phone"), address: text("address"), taxNumber: text("tax_number"), category: text("category"), notes: text("notes"), isActive: boolean("is_active").default(true).notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull() });
export const purchaseOrders = pgTable("purchase_orders", { id: uuid("id").defaultRandom().primaryKey(), projectId: uuid("project_id").references(() => projects.id, { onDelete: "cascade" }).notNull(), supplierId: uuid("supplier_id").references(() => suppliers.id, { onDelete: "restrict" }).notNull(), poNumber: text("po_number").notNull().unique(), status: procurementStatus("status").default("draft").notNull(), orderDate: timestamp("order_date", { withTimezone: true }), expectedDeliveryDate: timestamp("expected_delivery_date", { withTimezone: true }), subtotal: decimal("subtotal", { precision: 16, scale: 2 }).default("0").notNull(), taxAmount: decimal("tax_amount", { precision: 16, scale: 2 }).default("0").notNull(), totalAmount: decimal("total_amount", { precision: 16, scale: 2 }).default("0").notNull(), notes: text("notes"), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull() });
export const purchaseOrderItems = pgTable("purchase_order_items", { id: uuid("id").defaultRandom().primaryKey(), purchaseOrderId: uuid("purchase_order_id").references(() => purchaseOrders.id, { onDelete: "cascade" }).notNull(), boqItemId: uuid("boq_item_id").references(() => boqItems.id, { onDelete: "set null" }), description: text("description").notNull(), quantity: decimal("quantity", { precision: 14, scale: 3 }).default("0").notNull(), unit: text("unit").notNull(), unitRate: decimal("unit_rate", { precision: 14, scale: 2 }).default("0").notNull(), amount: decimal("amount", { precision: 16, scale: 2 }).default("0").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull() });
export const constructionActivities = pgTable("construction_activities", { id: uuid("id").defaultRandom().primaryKey(), projectId: uuid("project_id").references(() => projects.id, { onDelete: "cascade" }).notNull(), activityCode: text("activity_code").notNull(), name: text("name").notNull(), discipline: text("discipline"), status: workStatus("status").default("planned").notNull(), progress: integer("progress").default(0).notNull(), plannedQuantity: decimal("planned_quantity", { precision: 14, scale: 3 }).default("0").notNull(), actualQuantity: decimal("actual_quantity", { precision: 14, scale: 3 }).default("0").notNull(), unit: text("unit"), notes: text("notes"), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull() });
export const documents = pgTable("documents", { id: uuid("id").defaultRandom().primaryKey(), projectId: uuid("project_id").references(() => projects.id, { onDelete: "cascade" }).notNull(), title: text("title").notNull(), documentType: text("document_type").notNull(), discipline: text("discipline"), status: text("status").default("Draft").notNull(), fileName: text("file_name"), fileUrl: text("file_url"), revision: text("revision").default("1"), isApproved: boolean("is_approved").default(false).notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull() });
export const tasks = pgTable("tasks", { id: uuid("id").defaultRandom().primaryKey(), projectId: uuid("project_id").references(() => projects.id, { onDelete: "cascade" }).notNull(), title: text("title").notNull(), description: text("description"), status: text("status").default("open").notNull(), priority: text("priority").default("normal").notNull(), dueDate: timestamp("due_date", { withTimezone: true }), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull() });
export const rfis = pgTable("rfis", { id: uuid("id").defaultRandom().primaryKey(), projectId: uuid("project_id").references(() => projects.id, { onDelete: "cascade" }).notNull(), rfiNumber: text("rfi_number").notNull(), subject: text("subject").notNull(), question: text("question").notNull(), response: text("response"), status: text("status").default("open").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull() });
export const approvals = pgTable("approvals", { id: uuid("id").defaultRandom().primaryKey(), projectId: uuid("project_id").references(() => projects.id, { onDelete: "cascade" }).notNull(), subject: text("subject").notNull(), approvalType: text("approval_type").notNull(), status: text("status").default("pending").notNull(), comments: text("comments"), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull() });
export const costControl = pgTable("cost_control", { id: uuid("id").defaultRandom().primaryKey(), projectId: uuid("project_id").references(() => projects.id, { onDelete: "cascade" }).notNull(), costCode: text("cost_code").notNull(), description: text("description").notNull(), costType: text("cost_type").notNull(), amount: decimal("amount", { precision: 16, scale: 2 }).default("0").notNull(), status: text("status").default("draft").notNull(), notes: text("notes"), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull() });
export const auditLogs = pgTable("audit_logs", { id: uuid("id").defaultRandom().primaryKey(), projectId: uuid("project_id").references(() => projects.id, { onDelete: "set null" }), actorId: text("actor_id"), action: text("action").notNull(), entityType: text("entity_type").notNull(), entityId: text("entity_id"), metadata: text("metadata"), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() });
