"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

export default function SettingsPage() {
 const [theme,setTheme]=useState<"light"|"dark">("light");
 useEffect(()=>{const saved=window.localStorage.getItem("cs-theme");if(saved==="dark"||saved==="light")setTheme(saved)},[]);
 const changeTheme=(value:"light"|"dark")=>{setTheme(value);window.localStorage.setItem("cs-theme",value);document.documentElement.dataset.theme=value};
 return <main className="content standalone vercel-colour-module settings-page"><style>{`.vercel-colour-module{background:#f7f8fa;color:#111827;min-height:100vh}.vercel-colour-module .eyebrow{color:#64748b}.vercel-colour-module h1,.vercel-colour-module h2,.vercel-colour-module strong{color:#111827}.vercel-colour-module p{color:#64748b}.vercel-colour-module .workspace-card,.vercel-colour-module .kpi-card{background:#fff;border-color:#e5e7eb;box-shadow:0 1px 2px rgba(15,23,42,.03)}.vercel-colour-module .section-label,.vercel-colour-module .kpi-card span{color:#64748b}.settings-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;margin-bottom:12px}.settings-card{border:1px solid #e2e8f0;border-radius:12px;background:#fff;padding:20px}.settings-card h2{font-size:17px;margin-bottom:6px}.settings-card p{font-size:12px;margin-bottom:16px}.settings-option{display:flex;align-items:center;justify-content:space-between;gap:14px;padding:12px;border:1px solid #e2e8f0;border-radius:9px;background:#f8fafc}.settings-option strong{font-size:12px}.settings-option span{display:block;color:#64748b;font-size:10px;margin-top:3px}.settings-actions{display:flex;gap:8px;flex-wrap:wrap}.settings-links{display:grid;gap:8px}.settings-links a{display:flex;justify-content:space-between;align-items:center;padding:12px;border:1px solid #e2e8f0;border-radius:9px;color:#334155;text-decoration:none;font-size:12px;background:#fff}.settings-links a:hover{border-color:#bfdbfe;background:#eff6ff;color:#2563eb}.settings-note{padding:12px;border:1px solid #dbeafe;background:#eff6ff;border-radius:9px;color:#1e40af;font-size:11px;line-height:1.5}@media(max-width:800px){.settings-grid{grid-template-columns:1fr}}`}</style>
 <header className="topbar"><div><div className="eyebrow">System · Workspace</div><h1>Settings</h1><p>Workspace preferences, navigation controls and platform configuration for Creative Studios.</p></div><Link className="secondary-button" href="/">Dashboard</Link></header>
 <section className="kpi-grid"><div className="kpi-card"><span>Workspace</span><strong>Ready</strong><small>Creative Studios</small></div><div className="kpi-card"><span>Theme</span><strong>{theme==='light'?'Light':'Dark'}</strong><small>Saved on this device</small></div><div className="kpi-card"><span>Navigation</span><strong>Active</strong><small>Vercel workspace shell</small></div><div className="kpi-card"><span>Platform</span><strong>Vercel</strong><small>Next.js application</small></div></section>
 <div className="settings-grid">
  <section className="settings-card"><div className="section-label">Appearance</div><h2>Workspace theme</h2><p>Choose the interface preference used by this browser.</p><div className="settings-option"><div><strong>{theme==='light'?'Light workspace':'Dark workspace'}</strong><span>Local preference</span></div><div className="settings-actions"><button className="secondary-button" onClick={()=>changeTheme("light")}>Light</button><button className="secondary-button" onClick={()=>changeTheme("dark")}>Dark</button></div></div></section>
  <section className="settings-card"><div className="section-label">Navigation</div><h2>Workspace controls</h2><p>Open the operational areas directly from the shared application shell.</p><div className="settings-links"><Link href="/projects">Projects <span>→</span></Link><Link href="/notifications">Notifications <span>→</span></Link><Link href="/audit-log">Audit Trail <span>→</span></Link></div></section>
  <section className="settings-card"><div className="section-label">Governance</div><h2>Project controls</h2><p>Review the connected workflow from technical queries through approvals and construction.</p><div className="settings-links"><Link href="/rfis">RFIs <span>→</span></Link><Link href="/approvals">Approvals <span>→</span></Link><Link href="/reports">Reports <span>→</span></Link></div></section>
  <section className="settings-card"><div className="section-label">Platform</div><h2>Application configuration</h2><p>Creative Studios uses the shared project workspace and canonical data services across its Vercel modules.</p><div className="settings-note">Navigation labels and descriptions are managed through the workspace configuration. Operational records remain project-scoped and are stored through the shared application data layer.</div></section>
 </div>
 </main>;
}
