"use client";

import { useCallback, useEffect, useMemo, useState } from "react";

type Activity={id:string;projectId:string;activityCode:string;name:string;discipline:string|null;contractor:string|null;status:string;progress:number;plannedQuantity:string|number;actualQuantity:string|number;unit:string|null;plannedStart:string|null;plannedEnd:string|null;actualStart:string|null;actualEnd:string|null;notes:string|null;project?:{code:string;name:string}|null;boqItem?:{itemCode:string;description:string;quantity:string|number;unit:string}|null};
type Log={id:string;logDate:string;workDescription:string;quantityCompleted:string|number;unit:string|null;workforceCount:number;equipment:string|null;siteConditions:string|null;delayHours:string|number;delayReason:string|null;inspectionStatus:string;notes:string|null};
const n=(v:string|number|null|undefined)=>Number(v??0);
const date=(v:string|null|undefined)=>v?new Intl.DateTimeFormat(undefined,{year:"numeric",month:"short",day:"numeric"}).format(new Date(v)):"Not set";
const dateTime=(v:string)=>new Intl.DateTimeFormat(undefined,{year:"numeric",month:"short",day:"numeric",hour:"2-digit",minute:"2-digit"}).format(new Date(v));
const qty=(v:string|number)=>new Intl.NumberFormat(undefined,{maximumFractionDigits:3}).format(n(v));

export default function ActivityDetail({params}:{params:Promise<{id:string}>}){
 const [id,setId]=useState("");const [activity,setActivity]=useState<Activity|null>(null);const [logs,setLogs]=useState<Log[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");
 useEffect(()=>{void params.then(p=>setId(p.id))},[params]);
 const load=useCallback(async()=>{if(!id)return;setLoading(true);setError("");try{const [a,l]=await Promise.all([fetch(`/api/construction/${id}`,{cache:"no-store"}),fetch(`/api/construction/progress?activityId=${encodeURIComponent(id)}`,{cache:"no-store"})]);const ad=await a.json(),ld=await l.json();if(!a.ok)throw new Error(ad.error??"Unable to load activity.");if(!l.ok)throw new Error(ld.error??"Unable to load progress logs.");setActivity(ad.data);setLogs(Array.isArray(ld.data)?ld.data:[])}catch(e){setError(e instanceof Error?e.message:"Unable to load execution detail.")}finally{setLoading(false)}},[id]);
 useEffect(()=>{void load()},[load]);
 const cumulative=useMemo(()=>logs.reduce((s,l)=>s+n(l.quantityCompleted),0),[logs]);
 const planned=n(activity?.plannedQuantity);const remaining=Math.max(0,planned-cumulative);const calculated=planned>0?Math.min(100,Math.round(cumulative/planned*100)):0;
 if(loading)return <main className="projects-page construction-page"><div className="project-empty"><strong>Loading execution detail...</strong><span>Reading activity and daily site progress.</span></div></main>;
 if(error||!activity)return <main className="projects-page construction-page"><div className="project-alert error">{error||"Construction activity not found."}</div><a className="back-link" href="/construction">Back to Construction</a></main>;
 return <main className="projects-page construction-page"><header className="projects-header"><div><div className="eyebrow">Creative Studios / Construction / Execution</div><h1>{activity.activityCode}</h1><p>{activity.name}</p></div><div className="row-actions"><a className="back-link" href="/construction">Construction register</a><a className="primary-button" href={`/construction/progress?activityId=${encodeURIComponent(activity.id)}`}>Add daily progress</a></div></header>
 <section className="project-stats"><div className="project-stat"><span>Planned quantity</span><strong>{qty(planned)} {activity.unit??""}</strong></div><div className="project-stat"><span>Cumulative actual</span><strong>{qty(cumulative)} {activity.unit??""}</strong></div><div className="project-stat"><span>Remaining</span><strong>{qty(remaining)} {activity.unit??""}</strong></div><div className="project-stat"><span>Calculated progress</span><strong>{calculated}%</strong></div><div className="project-stat"><span>Daily logs</span><strong>{logs.length}</strong></div></section>
 <section className="project-layout"><section className="project-list-panel"><div className="list-toolbar"><div><div className="section-label">Execution summary</div><h2>{activity.name}</h2></div><span className={`project-status ${activity.status}`}>{activity.status.replace("_"," ")}</span></div><div className="form-grid"><div><div className="section-label">Project</div><strong>{activity.project?.code} · {activity.project?.name}</strong></div><div><div className="section-label">Discipline</div><strong>{activity.discipline||"General"}</strong></div><div><div className="section-label">Contractor</div><strong>{activity.contractor||"Not assigned"}</strong></div><div><div className="section-label">BOQ reference</div><strong>{activity.boqItem?`${activity.boqItem.itemCode} · ${activity.boqItem.description}`:"Not linked"}</strong></div><div><div className="section-label">Programme</div><strong>{date(activity.plannedStart)} → {date(activity.plannedEnd)}</strong></div><div><div className="section-label">Actual execution</div><strong>{date(activity.actualStart)} → {date(activity.actualEnd)}</strong></div></div>{activity.notes&&<div className="project-description">{activity.notes}</div>}</section>
 <section className="project-list-panel"><div className="list-toolbar"><div><div className="section-label">Daily site progress</div><h2>{logs.length} log{logs.length===1?"":"s"}</h2></div><button className="secondary-button" onClick={()=>void load()}>Refresh</button></div>{logs.length===0?<div className="project-empty"><strong>No daily progress recorded</strong><span>Add the first site progress log to begin accumulating actual quantity.</span></div>:<div className="project-table-wrap"><table className="project-table"><thead><tr><th>Date</th><th>Work description</th><th>Quantity</th><th>Workforce</th><th>Inspection</th><th>Delay</th><th>Conditions</th></tr></thead><tbody>{logs.map(l=><tr key={l.id}><td>{dateTime(l.logDate)}</td><td><strong>{l.workDescription}</strong>{l.notes&&<div className="project-description">{l.notes}</div>}</td><td><strong>{qty(l.quantityCompleted)}</strong> {l.unit??activity.unit??""}</td><td>{l.workforceCount}</td><td>{l.inspectionStatus}</td><td>{n(l.delayHours)>0?`${qty(l.delayHours)} h${l.delayReason?` · ${l.delayReason}`:""}`:"None"}</td><td>{l.siteConditions||"Not recorded"}</td></tr>)}</tbody></table></div>}</section></section></main>;
}
