import { NextResponse } from "next/server";
import { and, desc, eq } from "drizzle-orm";
import { z } from "zod";
import { getDb } from "@/db";
import { approvals, architectureWorks, boqItems, constructionActivities, documents, drawings, rfis, tasks } from "@/db/schema";
import { recordWorkflowEvent } from "@/lib/workflow-events";

export const runtime="nodejs";
export const dynamic="force-dynamic";

const documentStatus=z.enum(["Draft","Under Review","Approved","Superseded","Archived"]);
const optionalDate=z.string().datetime().optional().nullable();
const schemas={
  documents:z.object({projectId:z.string().uuid(),title:z.string().trim().min(1).max(200),documentType:z.string().trim().min(1).max(100),discipline:z.string().trim().max(100).optional().nullable(),status:documentStatus.optional(),fileName:z.string().trim().max(255).optional().nullable(),fileUrl:z.string().trim().max(1000).optional().nullable(),revision:z.string().trim().max(30).optional().nullable(),isApproved:z.boolean().optional()}),
  drawings:z.object({projectId:z.string().uuid(),drawingNumber:z.string().trim().min(1).max(100),title:z.string().trim().min(1).max(200),discipline:z.string().trim().min(1).max(100),drawingType:z.string().trim().max(100).optional(),revision:z.string().trim().max(30).optional(),status:z.string().trim().max(50).optional(),scale:z.string().trim().max(50).optional().nullable(),fileUrl:z.string().trim().max(1000).optional().nullable()}),
  boq:z.object({projectId:z.string().uuid(),drawingId:z.string().uuid().optional().nullable(),itemCode:z.string().trim().max(100),category:z.string().trim().min(1).max(120),element:z.string().trim().min(1).max(120),description:z.string().trim().min(1).max(2000),quantity:z.coerce.number().finite().min(0).max(999999999),unit:z.string().trim().min(1).max(30),rate:z.coerce.number().finite().min(0).max(999999999),amount:z.coerce.number().finite().min(0).max(999999999999),status:z.enum(["planned","in_progress","completed","on_hold"]).optional()}),
  architecture:z.object({projectId:z.string().uuid(),category:z.string().trim().min(1).max(120),description:z.string().trim().min(1).max(2000),status:z.enum(["planned","in_progress","completed","on_hold"]).optional(),progress:z.number().int().min(0).max(100).optional(),notes:z.string().trim().max(4000).optional().nullable()}),
  tasks:z.object({projectId:z.string().uuid(),title:z.string().trim().min(1).max(200),description:z.string().trim().max(4000).optional().nullable(),status:z.string().trim().max(50).optional(),priority:z.string().trim().max(50).optional(),dueDate:optionalDate}),
  rfis:z.object({projectId:z.string().uuid(),rfiNumber:z.string().trim().min(1).max(60),subject:z.string().trim().min(1).max(200),question:z.string().trim().min(1).max(5000),response:z.string().trim().max(5000).optional().nullable(),status:z.enum(["Open","Under Review","Answered","Closed","Cancelled","open","under_review","answered","closed","cancelled"]).optional(),raisedBy:z.string().trim().max(200).optional().nullable(),assignedTo:z.string().trim().max(200).optional().nullable(),priority:z.enum(["Low","Medium","High","Critical"]).optional(),dueDate:optionalDate,responseDate:optionalDate,drawingId:z.string().uuid().optional().nullable(),boqItemId:z.string().uuid().optional().nullable(),constructionActivityId:z.string().uuid().optional().nullable(),notes:z.string().trim().max(5000).optional().nullable(),reference:z.string().trim().max(500).optional().nullable()}),
  approvals:z.object({projectId:z.string().uuid(),subject:z.string().trim().min(1).max(200),approvalType:z.string().trim().min(1).max(100),approvalNumber:z.string().trim().max(60).optional().nullable(),status:z.enum(["Pending","In Review","Approved","Rejected","Returned","Cancelled","pending","in_review","approved","rejected","returned","cancelled"]).optional(),requestedBy:z.string().trim().max(200).optional().nullable(),reviewer:z.string().trim().max(200).optional().nullable(),dueDate:optionalDate,submittedAt:optionalDate,decidedAt:optionalDate,documentId:z.string().uuid().optional().nullable(),drawingId:z.string().uuid().optional().nullable(),rfiId:z.string().uuid().optional().nullable(),comments:z.string().trim().max(5000).optional().nullable()})
} as const;
const tables={documents,drawings,boq:boqItems,architecture:architectureWorks,tasks,rfis,approvals} as const;
type ModuleName=keyof typeof tables;
function moduleName(request:Request):ModuleName|null{const value=new URL(request.url).searchParams.get("module") as ModuleName|null;return value&&value in tables?value:null}
function validId(value:unknown){return typeof value==="string"&&z.string().uuid().safeParse(value).success}
async function parseBody(request:Request,module:ModuleName){return schemas[module].safeParse(await request.json().catch(()=>null))}
function toDate(value:unknown){return value?new Date(String(value)):null}
function normalizeValues(module:ModuleName,values:Record<string,unknown>){const normalized={...values};if(module==="architecture"){normalized.status??="planned";normalized.progress??=0}if(module==="tasks"){normalized.status??="open";normalized.priority??="normal";if(normalized.dueDate)normalized.dueDate=toDate(normalized.dueDate)}if(module==="rfis"){normalized.status??="Open";normalized.priority??="Medium";for(const key of ["dueDate","responseDate"]){if(normalized[key])normalized[key]=toDate(normalized[key])}}if(module==="approvals"){normalized.status??="Pending";for(const key of ["dueDate","submittedAt","decidedAt"]){if(normalized[key])normalized[key]=toDate(normalized[key])}}if(module==="documents"){normalized.status??="Draft";normalized.revision??="1";normalized.isApproved??=normalized.status==="Approved"}if(module==="drawings"){normalized.drawingType??="Plan";normalized.revision??="A";normalized.status??="Draft";normalized.scale??="1:100"}if(module==="boq"){const q=Number(normalized.quantity??0),r=Number(normalized.rate??0);normalized.status??="planned";normalized.amount=Number((q*r).toFixed(2))}return normalized}

async function validateRelations(module:ModuleName,values:Record<string,unknown>){
  const projectId=String(values.projectId);
  if(module==="rfis"){
    for(const [key,table] of [["drawingId",drawings],["boqItemId",boqItems],["constructionActivityId",constructionActivities]] as const){const id=values[key];if(id){const row=await getDb().select({id:table.id,projectId:table.projectId}).from(table).where(eq(table.id,String(id)));if(!row[0]||row[0].projectId!==projectId)return `${key} does not belong to the selected project.`;}}
  }
  if(module==="approvals"){
    for(const [key,table] of [["documentId",documents],["drawingId",drawings],["rfiId",rfis]] as const){const id=values[key];if(id){const row=await getDb().select({id:table.id,projectId:table.projectId}).from(table).where(eq(table.id,String(id)));if(!row[0]||row[0].projectId!==projectId)return `${key} does not belong to the selected project.`;}}
  }
  if(module==="boq"&&values.drawingId){const drawing=await getDb().select({id:drawings.id,projectId:drawings.projectId}).from(drawings).where(eq(drawings.id,String(values.drawingId)));if(!drawing[0]||drawing[0].projectId!==projectId)return "Drawing does not belong to the selected project."}
  return null;
}

function workflowDetails(module:ModuleName,row:any,previous?:any){
  if(module!=="rfis"&&module!=="approvals")return null;
  const isRfi=module==="rfis";
  const label=isRfi?`${row.rfiNumber} · ${row.subject}`:row.approvalNumber?`${row.approvalNumber} · ${row.subject}`:row.subject;
  const actor=isRfi?(row.raisedBy||row.assignedTo||"System"):(row.requestedBy||row.reviewer||"System");
  const statusChanged=previous&&previous.status!==row.status;
  const responseChanged=isRfi&&previous&&previous.response!==row.response&&row.response;
  let action=previous?`Updated ${isRfi?"RFI":"Approval"}`:`Created ${isRfi?"RFI":"Approval"}`;
  let title=previous?`${isRfi?"RFI":"Approval"} updated`:`${isRfi?"RFI":"Approval"} created`;
  let message=previous?`${label} was updated.`:`${label} was created.`;
  let recipient=isRfi?(row.assignedTo||null):(row.reviewer||null);
  let severity=isRfi&&["High","Critical"].includes(row.priority)?row.priority.toLowerCase():"normal";
  if(statusChanged){action=`Status changed to ${row.status}`;title=`${isRfi?"RFI":"Approval"} status changed`;message=`${label} is now ${row.status}.`;recipient=isRfi?(row.assignedTo||row.raisedBy||null):(row.reviewer||row.requestedBy||null);}
  if(responseChanged){action="Response recorded";title="RFI response received";message=`A response has been recorded for ${label}.`;recipient=row.raisedBy||null;severity="normal";}
  return {label,actor,action,title,message,recipient,severity};
}

export async function GET(request:Request){const module=moduleName(request);if(!module)return NextResponse.json({error:"Unsupported workspace module."},{status:400});const params=new URL(request.url).searchParams,projectId=params.get("projectId"),drawingId=params.get("drawingId");if(projectId&&!validId(projectId))return NextResponse.json({error:"Invalid project id."},{status:400});if(drawingId&&!validId(drawingId))return NextResponse.json({error:"Invalid drawing id."},{status:400});try{const table=tables[module] as any;const conditions=[] as any[];if(projectId)conditions.push(eq(table.projectId,projectId));if(module==="boq"&&drawingId)conditions.push(eq(table.drawingId,drawingId));const rows=await getDb().select().from(table).where(conditions.length?and(...conditions):undefined).orderBy(desc(table.createdAt));return NextResponse.json({data:rows})}catch(error){console.error(`GET /api/workspace?module=${module} failed`,error);return NextResponse.json({error:"Database is not configured or unavailable."},{status:503})}}

export async function POST(request:Request){const module=moduleName(request);if(!module)return NextResponse.json({error:"Unsupported workspace module."},{status:400});const parsed=await parseBody(request,module);if(!parsed.success)return NextResponse.json({error:"Invalid record data.",issues:parsed.error.flatten()},{status:400});try{const values=normalizeValues(module,parsed.data as Record<string,unknown>),relationError=await validateRelations(module,values);if(relationError)return NextResponse.json({error:relationError},{status:400});const table=tables[module] as any,result=await getDb().insert(table).values(values as any).returning(),row=(result as any[])[0];const event=workflowDetails(module,row);if(event){await recordWorkflowEvent({projectId:row.projectId,actor:event.actor,action:event.action,entityType:module.slice(0,-1),entityId:row.id,entityLabel:event.label,details:event.message,metadata:{status:row.status,priority:row.priority},notification:event.recipient?{title:event.title,message:event.message,recipient:event.recipient,severity:event.severity,actionUrl:module==="rfis"?"/rfis":"/approvals"}:null});}return NextResponse.json({data:row},{status:201})}catch(error){console.error(`POST /api/workspace?module=${module} failed`,error);return NextResponse.json({error:"Unable to create record."},{status:500})}}

export async function PATCH(request:Request){const module=moduleName(request),id=new URL(request.url).searchParams.get("id");if(!module)return NextResponse.json({error:"Unsupported workspace module."},{status:400});if(!validId(id))return NextResponse.json({error:"Invalid record id."},{status:400});const parsed=await parseBody(request,module);if(!parsed.success)return NextResponse.json({error:"Invalid record data.",issues:parsed.error.flatten()},{status:400});try{const table=tables[module] as any,existing=(await getDb().select().from(table).where(eq(table.id,id)))[0];if(!existing)return NextResponse.json({error:"Record not found."},{status:404});const values=normalizeValues(module,parsed.data as Record<string,unknown>),relationError=await validateRelations(module,values);if(relationError)return NextResponse.json({error:relationError},{status:400});const result=await getDb().update(table).set({...values as any,updatedAt:new Date()}).where(eq(table.id,id)).returning(),row=(result as any[])[0];if(!row)return NextResponse.json({error:"Record not found."},{status:404});const event=workflowDetails(module,row,existing);if(event&&(existing.status!==row.status||existing.response!==row.response||module==="approvals")){await recordWorkflowEvent({projectId:row.projectId,actor:event.actor,action:event.action,entityType:module.slice(0,-1),entityId:row.id,entityLabel:event.label,details:event.message,metadata:{fromStatus:existing.status,toStatus:row.status},notification:event.recipient?{title:event.title,message:event.message,recipient:event.recipient,severity:event.severity,actionUrl:module==="rfis"?"/rfis":"/approvals"}:null});}return NextResponse.json({data:row})}catch(error){console.error(`PATCH /api/workspace?module=${module}&id=${id} failed`,error);return NextResponse.json({error:"Unable to update record."},{status:500})}}

export async function DELETE(request:Request){const module=moduleName(request),id=new URL(request.url).searchParams.get("id");if(!module)return NextResponse.json({error:"Unsupported workspace module."},{status:400});if(!validId(id))return NextResponse.json({error:"Invalid record id."},{status:400});try{const table=tables[module] as any,existing=(await getDb().select().from(table).where(eq(table.id,id)))[0];if(!existing)return NextResponse.json({error:"Record not found."},{status:404});const result=await getDb().delete(table).where(eq(table.id,id)).returning({id:table.id}),row=(result as any[])[0];if(!row)return NextResponse.json({error:"Record not found."},{status:404});if(module==="rfis"||module==="approvals"){const event=workflowDetails(module,existing);await recordWorkflowEvent({projectId:existing.projectId,actor:event?.actor||"System",action:`Deleted ${module.slice(0,-1)}`,entityType:module.slice(0,-1),entityId:id,entityLabel:event?.label||null,details:`${event?.label||module} was deleted.`,metadata:{status:existing.status},notification:null});}return NextResponse.json({data:row})}catch(error){console.error(`DELETE /api/workspace?module=${module}&id=${id} failed`,error);return NextResponse.json({error:"Unable to delete record."},{status:500})}}
